- hosts: localhost
  gather_facts: false
  tasks:
    - hashicorp_vault:
        url: 'http://172.17.0.2:8200'
        secret_path: 
          - path: 'secrets2/secret1'
            keys:
              - "from_vault"

        approle_id: 0af6ba7e-670c-83ed-a5ae-3919aa0bf4fa
        approle_secret: 30139674-dedc-d3af-dcb7-0b48fbd5e563

    - debug:
        msg: '{{ from_vault }}'