- hosts: localhost
  gather_facts: false
  vars:
    paths1:
      - secret1/1
      - secret1/2
      - secret1/3

    paths2:
      - secret1/4
      - secret1/5
      - secret1/6
  tasks:
    - hashicorp_vault:
        url: 'http://172.17.0.2:8200'
        secret_path: 
          - '{{ paths1 }}'
          - '{{ paths2 }}'
          - 'kv/secret1'
          - path: 'kv_v1/v1_secret1'
            keys: 
              - 'v1_1_secret'

        approle_id: 7998b9fc-f602-0147-15ac-5abb2052f132
        approle_secret: b640b65f-0405-e46f-5363-cdd18011b513

    - debug:
        msg: '{{ test1 }} - {{ test2 }} - {{ test3 }} - {{ from_vault }} - {{ v1_1_secret }}'